######################################################################
# Automatically generated by qmake (3.1) Sun Feb 17 22:12:19 2019
######################################################################

TEMPLATE = app
CONFIG = console testcase qt debug_and_release
TARGET = tst_tengine
QT += testlib

INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += $$files(*.h)
HEADERS += $$files(commands/*.h,true)
HEADERS += $$files(dialogs/*.h,true)
HEADERS += $$files(platform/*.h)
HEADERS += $$files(widgets/*.h,true)

SOURCES += $$files(*.cpp)
SOURCES += $$files(commands/*.cpp,true)
SOURCES += $$files(dialogs/*.cpp,true)
SOURCES += $$files(widgets/*.cpp,true)

win32-msvc {
    HEADERS += $$files(platform/windows/*.h,true)
    SOURCES += $$files(platform/windows/*.cpp,true)
    INCLUDEPATH += ../packages/googletest/include
    CONFIG(release, debug|release){
        message(Release build!) #will print
    }
    CONFIG(debug, debug|release){
        message(Debug build!) #no print
    }
    LIBS += ../packages/googletest/debug/gmockd.lib
#    LIBS += ../packages/googletest/release/gmock.lib
}
CONFIG(debug_and_release):message(Release build!) #will print
CONFIG(debug, debug|release):message(Debug build!) #no print

include(../src/lib.pri)