name: Tests (Ubuntu / GCC)

on:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake ninja-build git pkg-config dpkg-dev \
            qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-l10n-tools qt6-qpa-plugins \
            libarchive-dev libicu-dev libgtest-dev libgmock-dev

      - name: Configure (CMake)
        run: cmake --preset Ubuntu-GCC-Ninja-debug

      - name: Build
        run: cmake --build --preset Ubuntu-GCC-Ninja-debug --parallel

      - name: Run tests (CTest)
        env:
          QT_QPA_PLATFORM: offscreen
        run: ctest --preset Ubuntu-GCC-Ninja-debug